import React from 'react';

export default class FormEdit extends React.Component{
    constructor(props){
        super(props);
        const dados = this.props.getPessoa(this.props.id);
        this.props.importarPessoa(dados.pessoa);
        
    };
    render(){
        return(
            <div className='form'>
                <label>Nome:
                    <input
                        name="nome"
                        type="text"
                        value={this.props.pessoa.nome}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>Nascimento:
                    <input
                        name="nascimento"
                        type="text"
                        value={this.props.pessoa.nascimento}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>RG:
                    <input
                        name="rg"
                        type="text"
                        value={this.props.pessoa.rg}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>CPF:
                    <input
                        name="cpf"
                        type="text"
                        value={this.props.pessoa.cpf}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>Endereço:
                    <input
                        name="endereco"
                        type="text"
                        value={this.props.pessoa.endereco}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>CEP:
                    <input
                        name="cep"
                        type="text"
                        value={this.props.pessoa.cep}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>Bairro:
                    <input
                        name="bairro"
                        type="text"
                        value={this.props.pessoa.bairro}
                        onChange={this.props.handlerChangePessoa}  
                    />
                </label>
                <label>Cidade:
                    <input
                        name="cidade"
                        type="text"
                        value={this.props.pessoa.cidade}
                        onChange={this.props.handlerChangePessoa} 
                    />
                </label>
                <label>Estado:
                    <input
                        name="estado"
                        type="text"
                        value={this.props.pessoa.estado}
                        onChange={this.props.handlerChangePessoa}  
                    />
                </label>
                <button className='button' onClick={ this.props.atualizarPessoa }>Atualizar</button>
            </div>
        );
    };
};